# application.properties

# DAO type: memory or database
dao.type=memory

# Database connection information
db.url=jdbc:mysql://localhost:3306/yourdatabase
db.username=yourusername
db.password=yourpassword